version: '3.1'
services:
  web:
    image: nginx:1.22.0-alpine
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
      - NGINX_PORT=443
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/ssl:ro
    networks:
      - vpcbr

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.66.65.0/24